os: Visual Studio 2015
version: 1.0.{build}
environment:
  QTDIR: C:\Qt\5.5\msvc2013_64

  matrix:
  - BUILD_VARIANT: debug
  - BUILD_VARIANT: release

install:
  - cmd: git submodule update --init --recursive
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - cmd: set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\install

build_script:
- cmd: >-

    qbs setup-toolchains --detect

    qbs setup-qt %QTDIR%\bin\qmake.exe qt

    qbs config defaultProfile qt

    cd %APPVEYOR_BUILD_FOLDER%\src

    qbs --command-echo-mode command-line --clean-install-root qbs.installRoot:%INSTALL_DIR% %BUILD_VARIANT%

    windeployqt --%BUILD_VARIANT% --no-system-d3d-compiler --no-translations --no-qmltooling --qmldir %APPVEYOR_BUILD_FOLDER%\src\qml %INSTALL_DIR%

    windeployqt --%BUILD_VARIANT% --no-system-d3d-compiler --no-translations --no-qmltooling --qmldir %APPVEYOR_BUILD_FOLDER%\modules\qml-material\modules\material %INSTALL_DIR%

    dir

artifacts:
- path: install
  name: ForcesSimulation
