os: Visual Studio 2015
version: 1.0.{build}

environment:
  QTDIR: C:\Qt\5.5\msvc2013_64
  PYTHON: "C:\\Python34"
  INSTALL_DIR: "%APPVEYOR_BUILD_FOLDER%\\install"
  matrix:
  - BUILD_VARIANT: debug
    ADDITIONAL_PARAMS: "qbs.installRoot:%INSTALL_DIR%"
    TAKE_SCREENSHOT: echo "Not implemented yet"
  - BUILD_VARIANT: release
    ADDITIONAL_PARAMS: "qbs.installRoot:%INSTALL_DIR%"
    TAKE_SCREENSHOT: echo "Not implemented yet"
  - BUILD_VARIANT: release
    ADDITIONAL_PARAMS: "qbs.installRoot:%APPVEYOR_BUILD_FOLDER%\\install project.justRunExperiments:true"
    TAKE_SCREENSHOT: "%INSTALL_DIR%\\ForcesSimlation\\ForcesSimlation && python %APPVEYOR_BUILD_FOLDER%\\scripts\\plot.py --input %APPVEYOR_BUILD_FOLDER%\\fsim_data --out %INSTALL_DIR%\\screenshots"
    INSTALL_MATPLOTLIB: yes

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl -fsS -o rclone.zip http://downloads.rclone.org/rclone-v1.28-windows-386.zip && 7z e rclone.zip
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%;%cd%;%cd%\rclone-v1.28-windows-386
  - cmd: set FSIM_DIR=%INSTALL_DIR%\\ForcesSimlation
  - cmd: set FSIM_EXECUTABLE=%FSIM_DIR%\ForcesSimlation
  - cmd: set SCRIPTS_DIR=%APPVEYOR_BUILD_FOLDER%\scripts
  - cmd: set FSIM_DATA_FILE_NAME=%APPVEYOR_BUILD_FOLDER%\fsim_data
  - cmd: set SCREENSHOTS_DIR=%INSTALL_DIR%\screenshots
  - cmd: python -m pip install --upgrade pip && pip install --upgrade wheel -V && pip install --upgrade PySide -V && pip install --upgrade --pre http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1956+aab2833-cp34-cp34m-win32.whl -V
  - cmd: IF DEFINED INSTALL_MATPLOTLIB ( pip install --upgrade --pre https://pypi.python.org/packages/cp34/m/matplotlib/matplotlib-1.5.1-cp34-none-win32.whl -V )
  - python --version
  - pip --version

build_script:
- cmd: >-

    qbs setup-toolchains --detect

    qbs setup-qt %QTDIR%\bin\qmake.exe qt

    qbs config defaultProfile qt

    qbs --file %APPVEYOR_BUILD_FOLDER% --command-echo-mode command-line --clean-install-root %ADDITIONAL_PARAMS% %BUILD_VARIANT%

    windeployqt --%BUILD_VARIANT% --no-system-d3d-compiler --no-translations --no-qmltooling --qmldir %APPVEYOR_BUILD_FOLDER%\src\qml %FSIM_DIR%

    windeployqt --%BUILD_VARIANT% --no-system-d3d-compiler --no-translations --no-qmltooling --qmldir %APPVEYOR_BUILD_FOLDER%\modules\qml-material\modules\material %FSIM_DIR%

# copy deployed files to needed locations (will be fixed in the future)
- cmd: >-

    cd %FSIM_DIR%

    IF EXIST iconengines\ ( rclone copy iconengines\ data\plugins\iconengines\ ) && IF EXIST imageformats\ ( rclone copy imageformats\ data\plugins\imageformats\ ) && IF EXIST platforms\ ( rclone copy platforms\ data\plugins\platforms\ ) && IF EXIST Qt\ ( rclone copy Qt\ data\qml\Qt\ ) && IF EXIST QtGraphicalEffects\ ( rclone copy QtGraphicalEffects\ data\qml\QtGraphicalEffects\ ) && IF EXIST QtQml\ ( rclone copy QtQml\ data\qml\QtQml\ ) && IF EXIST QtQuick\ ( rclone copy QtQuick\ data\qml\QtQuick\ ) && IF EXIST QtQuick.2\ ( rclone copy QtQuick.2\ data\qml\QtQuick.2\ )

    IF EXIST iconengines\ ( rmdir iconengines /s /q ) && IF EXIST imageformats\ ( rmdir imageformats /s /q ) && IF EXIST platforms\ ( rmdir platforms /s /q ) && IF EXIST Qt\ ( rmdir Qt /s /q ) && IF EXIST QtGraphicalEffects\ ( rmdir QtGraphicalEffects /s /q ) && IF EXIST QtQml\ ( rmdir QtQml /s /q ) && IF EXIST QtQuick\ ( rmdir QtQuick /s /q ) && IF EXIST QtQuick.2\ ( rmdir QtQuick.2 /s /q ) && IF EXIST bearer\ ( rmdir bearer /s /q )

    %TAKE_SCREENSHOT%

artifacts:
- path: install
  name: ForcesSimulation
